---
title: "Dropout dynamics"
author: "Dominik Glandorf"
date: "2022-11-29"
output: pdf_document
---
```{r, include=F}
setwd('~/EWS/')
source('read_data.R')


terms = get_term_features()
terms_first_year = terms %>%
  group_by(mellon_id) %>% 
  filter(term_code < min(term_code) + 100) %>% 
  summarize(first_year_num_terms = n(),
            first_year_term_span = max(term_code) - min(term_code)) %>% 
  mutate(first_year_term_span = recode(first_year_term_span,
                                       `0` = 1, `11` = 2, `22` = 3, `89` = 3))

terms_second_year = terms %>%
  group_by(mellon_id) %>% 
  filter(term_code < min(term_code) + 200) %>% 
  summarize(second_year_num_terms = n(),
            second_year_term_span = max(term_code) - min(term_code)) %>% 
  mutate(second_year_term_span = recode(second_year_term_span,
                                       `0` = 1, `11` = 2, `22` = 3, `89` = 1,
                                       `100` = 4, `111` = 5, `122` = 6, `189` = 6))

terms_third_year = terms %>%
  group_by(mellon_id) %>% 
  filter(term_code < min(term_code) + 300) %>% 
  summarize(third_year_num_terms = n(),
            third_year_term_span = max(term_code) - min(term_code)) %>% 
  mutate(third_year_term_span = recode(third_year_term_span,
                                       `0` = 1, `11` = 2, `22` = 3, `89` = 1,
                                       `100` = 4, `111` = 5, `122` = 6, `189` = 6,
                                       `200` = 7, `211` = 8, `222` = 9, `289` = 9))

students = get_student_sub()
students = students %>%
  left_join(terms_first_year) %>%
  left_join(terms_second_year) %>%
  left_join(terms_third_year)
```

```{r, fig.width=12, fig.height=12}
plot1 = students %>% group_by(first_year_num_terms) %>% summarize(dropout_rate = 1 - mean(graduated),
                                               n_students = n()) %>%
  ggplot(aes(x=first_year_num_terms, y=dropout_rate, width=n_students/nrow(students))) +
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$first_year_num_terms), max(students$first_year_num_terms), by = 1)) +
  labs(title="Dropout rate by total number of terms enrolled up to first year", x="", y="")
  
plot2 = students %>% group_by(first_year_term_span) %>% summarize(dropout_rate = 1 - mean(graduated),
                                               n_students = n()) %>%
  mutate(unconsidered = max(first_year_term_span) - first_year_term_span >= 4 ) %>% 
  ggplot(aes(x=first_year_term_span, y=dropout_rate, width=n_students/nrow(students), fill=unconsidered)) +
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$first_year_term_span), max(students$first_year_term_span), by = 1)) +
  labs(title="Dropout rate by span of terms enrolled up to first year", x="", y="", fill="Dropped out\nper definition") +
  annotate("text", x = Inf, y =0.9, label = "bar width = nr. of students", hjust = 1, vjust = 1, size = 5) +
  scale_fill_manual(values = c("FALSE" = "#00BFC4", "TRUE" = "#F8766D")) +
  theme(legend.position = c(0.92, 0.5))



plot3 = students %>% group_by(second_year_num_terms) %>% summarize(dropout_rate = 1 - mean(graduated),
                                               n_students = n()) %>%
  ggplot(aes(x=second_year_num_terms, y=dropout_rate, width=n_students/nrow(students))) +
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$second_year_num_terms), max(students$second_year_num_terms), by = 1)) +
  labs(title="Dropout rate by total number of terms enrolled up to second year", x="", y="")

plot4 = students %>% group_by(second_year_term_span) %>% summarize(dropout_rate = 1 - mean(graduated),
                                               n_students = n()) %>%
  mutate(unconsidered = max(second_year_term_span) - second_year_term_span >= 4 ) %>% 
  ggplot(aes(x=second_year_term_span, y=dropout_rate, width=n_students/nrow(students), fill=unconsidered)) +
  geom_bar(stat="identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$second_year_term_span), max(students$second_year_term_span), by = 1)) +
  labs(title="Dropout rate by span of terms enrolled up to second year", x="", y="", fill="Dropped out\nper definition")+
  scale_fill_manual(values = c("FALSE" = "#00BFC4", "TRUE" = "#F8766D"))+
  theme(legend.position = c(0.92, 0.5))


plot5 <- students %>%
  group_by(third_year_num_terms) %>%
  summarize(dropout_rate = 1 - mean(graduated),
            n_students = n()) %>%
  ggplot(aes(x = third_year_num_terms, y = dropout_rate, width = n_students / nrow(students))) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$third_year_num_terms), max(students$third_year_num_terms), by = 1)) +
  labs(title = "Dropout rate by total number of terms enrolled up to third year", x = "", y = "")

plot6 <- students %>%
  group_by(third_year_term_span) %>%
  summarize(dropout_rate = 1 - mean(graduated),
            n_students = n()) %>%
  mutate(unconsidered = max(third_year_term_span) - third_year_term_span >= 4) %>%
  ggplot(aes(x = third_year_term_span, y = dropout_rate, width = n_students / nrow(students), fill = unconsidered)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, 1, by = 0.1)) +
  scale_x_continuous(breaks = seq(min(students$third_year_term_span), max(students$third_year_term_span), by = 1)) +
  labs(title = "Dropout rate by span of terms enrolled up to third year", x = "", y = "", fill = "Dropped out\nper definition") +
  scale_fill_manual(values = c("FALSE" = "#00BFC4", "TRUE" = "#F8766D"))+
  theme(legend.position = c(0.92, 0.5))



library(gridExtra)

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol = 2)
```
# What are the overall rates?
```{r}
students %>% summarize(dropout_rate = 1 - mean(graduated),
                                               n_students = n())
```
```{r}
students %>% 
  filter(max(second_year_term_span) - second_year_term_span < 4) %>%
  summarize(dropout_rate = 1 - mean(graduated),
            n_students = n())
```
```{r}
students %>% 
  filter(max(third_year_term_span) - third_year_term_span < 4) %>%
  summarize(dropout_rate = 1 - mean(graduated),
            n_students = n())
28561/30501
```


# When does dropout happen?
```{r, echo=F}
ggplot(students, aes(fill=!graduated, x=num_terms)) + 
    geom_bar(position="stack", stat="count") +
    labs(title = "Distribution of dropout",
       x = "Term number",
       y = "Frequency", fill="Dropout") +
  ylim(0, 5000)
```
```{r, echo=F}

library(scales)
stud = students[!is.na(students$dropout),]
dropped_out = data.frame(term=c(0:18), number=sapply(c(0:18), FUN=function(i) nrow(stud[stud$dropout==T&stud$num_terms<=i,])))
ggplot(dropped_out,aes(x=term, y=number/max(number)))+
  geom_bar(stat="identity") +
  scale_y_continuous(labels=percent) +
  labs(title = "Cumulative histogram of dropouts",
       x = "Term number",
       y = "Share")
```

